[features]
seeds = false
skip-lint = false
[programs.localnet]
voting = "Ec1HB25VENo6m1TUVXsP49yhHHXcbdHNd889qFkkqCkf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/androidrighthand/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
